name: KdB scheduled update

on:
  schedule:
    - cron: '0 18 1 * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install requests
      - name: Synchronize the csv file with an up-to-date one
        run: |
          cd kdb/update-kdb
          python update-kdb.py False
          cp ../kdb.json ../../docs/
          cd ../../
      - name: Push and Commit
        env:
          TZ: Asia/Tokyo
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git config pull.rebase true
          git add .
          git commit -m "update kdb data: $(date +%Y%m%d)"
          git pull origin master
          git push origin master